<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SPTDir Condition="'$(SPTDir)' == ''">S:\SPT-Dev\4.1</SPTDir>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>BossNotifier.fika</AssemblyName>
    <RootNamespace>BossNotifier.Packets</RootNamespace>
    <generateassemblyinfo>false</generateassemblyinfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="com.fika.core">
      <HintPath>$(SPTDir)\BepInEx\plugins\Fika\Fika.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>

